//
//  SupportDocsViewController.swift
//  SupportDocs
//
//  Created by Zheng on 10/18/20.
//

import SwiftUI

// MARK: - iOS

#if !os(macOS)
import UIKit

/**
 UIKit wrapper for `SupportDocsView`
 */
public class SupportDocsViewController: UIViewController {
    /**
     Instantiate SupportDocs in your app.
     
     - parameter dataSourceURL: URL of the JSON file, where SupportDocs gets its data. This is generated by the GitHub Action.
     - parameter options: Options used for configuring SupportDocs. This is optional (mostly for changing the SupportDocs' appearance).
     */
    public init(dataSourceURL: URL, options: SupportOptions = SupportOptions()) {
        self.dataSourceURL = dataSourceURL
        self.options = options
        super.init(nibName: nil, bundle: nil)
    }
    
    @available(*, unavailable)
    public required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    /**
     URL of the JSON file, where SupportDocs gets its data. This is generated by the GitHub Action.
     */
    public var dataSourceURL: URL
    
    /**
     Options used for configuring SupportDocs. This is optional (mostly for changing the SupportDocs' appearance).
     */
    public var options = SupportOptions()
    
    override public func loadView() {
        /**
         Instantiate the base `view`.
         */
        view = UIView()

        /**
         Create a `SupportDocsView`.
         */
        var supportDocsView = SupportDocsView(
            dataSourceURL: dataSourceURL,
            options: options
        )
        
        /**
         Set the dismiss button handler.
         */
        supportDocsView.donePressed = { [weak self] in
            self?.dismiss(animated: true, completion: nil)
        }
        
        /**
         Host `supportDocsView` in a view controller.
         */
        let hostedSupportDocs = UIHostingController(rootView: supportDocsView)
        
        /**
         Embed `hostedSupportDocs`.
         */
        self.addChild(hostedSupportDocs)
        view.addSubview(hostedSupportDocs.view)
        hostedSupportDocs.view.frame = view.bounds
        hostedSupportDocs.view.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        hostedSupportDocs.didMove(toParent: self)
    }
}

// MARK: - macOS

#elseif os(macOS)
import Cocoa

/**
 Cocoa/AppKit wrapper for `SupportDocsView`
 */
public class SupportDocsViewController: NSViewController {
    /**
     Instantiate SupportDocs in your app.
     
     - parameter dataSourceURL: URL of the JSON file, where SupportDocs gets its data. This is generated by the GitHub Action.
     - parameter options: Options used for configuring SupportDocs. This is optional (mostly for changing the SupportDocs' appearance).
     */
    public init(dataSourceURL: URL, options: SupportOptions = SupportOptions()) {
        self.dataSourceURL = dataSourceURL
        self.options = options
        super.init(nibName: nil, bundle: nil)
    }
    
    @available(*, unavailable)
    public required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    /**
     URL of the JSON file, where SupportDocs gets its data. This is generated by the GitHub Action.
     */
    public var dataSourceURL: URL
    
    /**
     Options used for configuring SupportDocs. This is optional (mostly for changing the SupportDocs' appearance).
     */
    public var options = SupportOptions()
    
    override public func loadView() {
        /**
         Instantiate the base view
         */
        view = NSView()

        /**
         Create a `SupportDocsView`
         */
        var supportDocsView = SupportDocsView(
            dataSourceURL: dataSourceURL,
            options: options
        )
        
        /**
         Present view controller as sheet
         */
        self.parent?.presentAsSheet(self)
        
        /**
         Set the dismiss button handler
         */
        supportDocsView.donePressed = { [weak self] in
            self?.dismiss()
        }
        
        /**
         Host `supportDocsView` in a view controller
         */
        let hostedSupportDocs = NSHostingController(rootView: supportDocsView)
        
        /**
         Embed `hostedSupportDocs`
         */
        self.addChild(hostedSupportDocs)
        view.addSubview(hostedSupportDocs.view)
        hostedSupportDocs.view.frame = view.bounds
        hostedSupportDocs.view.autoresizingMask = [.width, .height]
    }
}
#endif
