//
//  SupportOptions+URLs.swift
//  SupportDocsSwiftUI
//
//  Created by Zheng on 10/25/20.
//

import Foundation

public extension SupportOptions {
    
    /**
     `URL` of the data source JSON and a custom 404 error page.
     */
    struct URLs {
     
        /**
         `URL` of the data source JSON and a custom 404 error page.
         
         - parameter dataSource: The JSON file where SupportDocs gets its data. This is generated by the GitHub Action. An example file can be found at [https://asdasdasdasd](https://TODOTODO)
         - parameter error404: Web page to display in case something goes wrong.
         */
        public init(
            dataSource: URL = URL(string: "https://google.com")!,
            error404: URL = URL(string: "https://google.com")!
        ) {
            self.dataSource = dataSource
            self.error404 = error404
        }
        
        /**
         The JSON file where SupportDocs gets its data. This is generated by the GitHub Action.
         
         An example file can be found at [https://asdasdasdasd](https://TODOTODO)
        */
        public var dataSource: URL = URL(string: "https://google.com")!
        
        /**
         Web page to display in case something goes wrong.
         */
        public var error404: URL = URL(string: "https://google.com")!
    }
}
